#!/bin/sh

# ==========================
# Configuración de rutas
# ==========================
BASE_DIR="$(cd "$(dirname "$0")/.." && pwd)"

# Detectar directorio de temas según entorno
if [ -d "$HOME/.local/share/themes/Lumina" ]; then
    THEME_DIR="$HOME/.local/share/themes/Lumina"
else
    THEME_DIR="$HOME/.themes/Lumina"
fi

BUILD_FILE="$BASE_DIR/LUMINA_BUILD"

# Detectar idioma
USER_LANG="${LANG%%.*}"

# ==========================
# Mensajes por idioma
# ==========================
if [ "${USER_LANG#es}" != "$USER_LANG" ]; then
    MSG_BUILD_INFO="Información de la build:"
    MSG_BUILD_NOT_FOUND="⚠ LUMINA_BUILD no encontrado"
    MSG_MODE_DRY="Modo: simulación"
    MSG_CLEANUP_START="Lumina UI – Cleanup Mode"
    MSG_CLEANUP_FINAL="Cleanup finalizado"
    MSG_FILE_DELETE="✖ Eliminado"
    MSG_FILE_WOULD_DELETE="⚠ Se eliminaría"
    MSG_VERSION_NOT_FOUND="✖ Archivo VERSION no encontrado"
    MSG_VERSION_LABEL="Versión actual"
else
    MSG_BUILD_INFO="Build information:"
    MSG_BUILD_NOT_FOUND="⚠ LUMINA_BUILD not found"
    MSG_MODE_DRY="Mode: dry-run"
    MSG_CLEANUP_START="Lumina UI – Cleanup Mode"
    MSG_CLEANUP_FINAL="Cleanup finished"
    MSG_FILE_DELETE="✖ Deleted"
    MSG_FILE_WOULD_DELETE="⚠ Would delete"
    MSG_VERSION_NOT_FOUND="✖ VERSION file not found"
    MSG_VERSION_LABEL="Current version"
fi

# ==========================
# Mostrar información de la build
# ==========================
if [ -f "$BUILD_FILE" ]; then
    echo ""
    echo "$MSG_BUILD_INFO"
    echo "-----------------------------------------"
    cat "$BUILD_FILE"
else
    echo ""
    echo "$MSG_BUILD_NOT_FOUND"
fi

# ==========================
# Modo dry-run o apply
# ==========================
MODE="apply"
[ "$1" = "--dry-run" ] && MODE="dry"

if [ ! -f "$BUILD_FILE" ]; then
    echo "$MSG_VERSION_NOT_FOUND"
    exit 1
fi

CURRENT_VERSION="$(cat "$BUILD_FILE")"

echo "========================================="
echo " $MSG_CLEANUP_START"
echo " $MSG_VERSION_LABEL: $CURRENT_VERSION"
[ "$MODE" = "dry" ] && echo " $MSG_MODE_DRY"
echo "========================================="

# ==========================
# Función de limpieza
# ==========================
clean_dir() {
    DIR="$1"
    [ -d "$DIR" ] || return

    for f in "$DIR"/*.scss; do
        [ -f "$f" ] || continue

        if grep -q "Generated by tools" "$f"; then
            if ! grep -q "Version: $CURRENT_VERSION" "$f"; then
                if [ "$MODE" = "dry" ]; then
                    echo "$MSG_FILE_WOULD_DELETE: $(basename "$f")"
                else
                    rm "$f"
                    echo "$MSG_FILE_DELETE: $(basename "$f")"
                fi
            fi
        fi
    done
}

# ==========================
# Limpiar todos los grupos
# ==========================
for DIR in \
    "$THEME_DIR/cinnamon/shell" \
    "$THEME_DIR/gtk-3.0/interface" \
    "$THEME_DIR/gtk-3.20/interface" \
    "$THEME_DIR/gtk-3.24/interface" \
    "$THEME_DIR/gtk-4.0/interface" \
    "$THEME_DIR/gnome-shell" \
    "$THEME_DIR/metacity-1" \
    "$THEME_DIR/xfwm4" \
    "$THEME_DIR/kde"
do
    clean_dir "$DIR"
done

# ==========================
# Fin del cleanup
# ==========================
echo "========================================="
echo " $MSG_CLEANUP_FINAL"
echo "========================================="
