#!/bin/sh

BASE_DIR="$(cd "$(dirname "$0")/.." && pwd)"
THEME_DIR="$HOME/.local/share/themes/Lumina"
VERSION_FILE="$BASE_DIR/VERSION"

MODE="apply"
[ "$1" = "--dry-run" ] && MODE="dry"

if [ ! -f "$VERSION_FILE" ]; then
    echo "✖ Archivo VERSION no encontrado"
    exit 1
fi

CURRENT_VERSION="$(cat "$VERSION_FILE")"

echo "========================================="
echo " Lumina UI – Cleanup Mode"
echo " Versión actual: $CURRENT_VERSION"
[ "$MODE" = "dry" ] && echo " Modo: simulación"
echo "========================================="

clean_dir() {
    DIR="$1"
    [ -d "$DIR" ] || return

    for f in "$DIR"/*.scss; do
        [ -f "$f" ] || continue

        if grep -q "Generated by tools" "$f"; then
            if ! grep -q "Version: $CURRENT_VERSION" "$f"; then
                if [ "$MODE" = "dry" ]; then
                    echo "⚠ Se eliminaría: $(basename "$f")"
                else
                    rm "$f"
                    echo "✖ Eliminado: $(basename "$f")"
                fi
            fi
        fi
    done
}

clean_dir "$THEME_DIR/cinnamon/shell"
clean_dir "$THEME_DIR/gtk-3.0/interface"
clean_dir "$THEME_DIR/gtk-3.20/interface"
clean_dir "$THEME_DIR/gtk-3.24/interface"
clean_dir "$THEME_DIR/gtk-4.0"
clean_dir "$THEME_DIR/gnome-shell"
clean_dir "$THEME_DIR/metacity-1"
clean_dir "$THEME_DIR/xfwm4"
clean_dir "$THEME_DIR/kde"

echo "========================================="
echo " Cleanup finalizado"
echo "========================================="

